# Generated by Django 3.2.13 on 2022-05-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dog_name',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
