# Generated by Django 3.2.13 on 2022-05-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_dog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dog_name',
            field=models.CharField(max_length=140),
        ),
    ]
