# Generated by Django 3.2.13 on 2022-05-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_dog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dog_name',
            field=models.CharField(max_length=150),
        ),
    ]
