# Generated by Django 3.2.13 on 2022-05-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_dog_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_comments',
        ),
    ]
